### ISSUE TITLE
Image Naming

### ISSUE THREAD

**Issue by vibhatha** [cybertraining-dsc/fa20-523-301#4]
https://github.com/cybertraining-dsc/fa20-523-301/tree/master/project/images

Please make sure the image extension names are in lower case. For instance, we see there are two images with 
PNG extension. Please rename it to .png and update the project.md.

**Comment by ghemmer** [comment]
Roger that. I'm updating on Github now. I will update the notebook and the report tonight.

**Comment by laszewsk** [comment]
I fixed your project.md with lower case .png

check the build and review, it may take up to 10 minutes for the changes to show in the web page, also make sure to clear your cache when viewing your report on cybertraining-dsc as we see some students that seem not to know how browser caches work and are confused why they do not see the updates.

**Comment by ghemmer** [comment]
Thank you, Dr. Laszewski. I appreciate the help!

I'll verify the build tonight after work.
